package exceptionHandling0;
public class Example08 {

	public static void main(String[] args) {
		
	}
	static int m1() {
		try {
			System.out.println("in try");
			return 10;
		}
		catch(ArithmeticException e) {
			System.out.println("in catch");
			return 20;
		}
	}
}